app:
    resource: '@AppBundle/Controller/'
    type: annotation

places:
    resource: AppBundle\Controller\PlaceController
    type: rest

prices:
    resource: AppBundle\Controller\Place\PriceController
    type: rest

users:
    resource: AppBundle\Controller\UserController
    type: rest